services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: example_api
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - c:/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306" # Host port 3306 -> container port 3306
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
     - "8080:80" # Access phpMyAdmin at http://localhost:8080